name: 'Filter SARIF'
description: 'Filter SARIF results by path'
inputs:
  patterns:
    description: 'Patterns for the results to remove. If a pattern starts with "-", it is an exclusion pattern, otherwise, it is an inclusion pattern.'
    required: true
  input:
    description: 'Path to the input SARIF file'
    required: true
  output:
    description: 'Path to the input SARIF file'
    required: true
runs:
  using: "composite"
  steps:
    - name: filter
      run: |
        unset LD_PRELOAD
        python3 "$GITHUB_ACTION_PATH/filter_sarif.py" --input "${{ inputs.input }}" --output "${{ inputs.output }}" --split-lines -- "${{ inputs.patterns }}"
      shell: bash
